### PR TITLE
Migrated Remit to use Amazon Signature v2

### PR DESCRIPTION
**Pull request by kevinmtrowbridge**
Hi Tyler,

I've been using Remit in my project http://snailmailr.com for the past year or so.  I needed to update it in response to the Amazon signature v1 to v2 migration, so I thought I'd submit the changes back to the community.

Amazon claims they stopped supporting signature v1 on November 1st.  Since Remit implements currently only v1, new users won't be able to to use it without these changes.  (In practice, they were still supporting v1 as of last night, I know because it continued to work on Snailmailr until I changed it over.  ;)  However, I suppose they might turn it off at any time.)

Thanks for writing Remit & Relax -- it saved me a lot of work!  I did my best with the changes and it all works, however, as the original author of the library, you will surely have opinions about how I did it.  Please let me know if there are betters ways to make those changes.

Regards,
Kevin Trowbridge

### CODE REVIEW

**Comment by tylerhunt** [comment]
Thank you for the commit and pull request. There's another guy I'm working with to get a similar update merged in right now, as well as some other additions that he's contributed. I'll be sure to pass this on to him so we can take the best of both implementations for the merge.

Glad you're finding Remit useful, and appreciate your contribution,

Tyler

**Comment by pboling** [comment]
Pulled in, 11 failing specs.  Current tylerhunt master will be moved into a branch, and will be given the version number 0.1.0
The nyc-ruby fork of remit will become master and be used to release 2.0 versions (skipping 1.0, leaving it for the old api if needed) of the gem, based on the new api.

**Comment by kevinmtrowbridge** [comment]
Hi Peter,

Thanks for taking a look at it.  Not sure if it was helpful.  The tests all passed locally, not sure why they were failing for you?  Perhaps something to do with versions.  In any case, I am sure it's my error.  Thanks for taking over the maintenance of the gem, I will keep my eye on the nyc-ruby fork of remit.

Regards,
Kevin

**Comment by pboling** [comment]
The failures may have been in the integration tests.  I didn't pay too much attention to them, as I no longer use the old API.  I have moved what was master into a new branch called api2007, and released remit 0.0.6 with your changes.  I will now merge nyc-ruby's remit into master and release a remit 2.0 on the new Amazon API.

**Pull request merged**
